#!/bin/sh
uci set system.@system[0].timezone='MSK-3'
uci set system.@system[0].zonename='Europe/Moscow'
uci commit system

MAC=$(cat /sys/class/net/br-lan/address 2>/dev/null | tr -d ':' | tr 'A-F' 'a-f')
PASS=$(printf "%stests" "${MAC}" | sha256sum | cut -c1-16)
printf "%s\n%s\n" "$PASS" "$PASS" | passwd root

exit 0
